In [1]:
import numpy as np

In [2]:
import tinygrad as tg
from tinygrad import nn
from tinygrad.nn import optim
from tinygrad.tensor import Tensor
from tinygrad.helpers import getenv
from tinygrad.ops import GlobalCounters


In [4]:
import pandas as pd

In [5]:
import numpy as np

In [6]:
import matplotlib.pyplot as plt

# Tensors in tinygrad are just syntactic sugar for numpy arrays

## scalar in tinygrad
scalars in tinygrad are also tensors

In [7]:
x = Tensor([1.23232])
Tensor

tinygrad.tensor.Tensor

# Initialising Tensors

## directly from data. (is type auto inferred?) seems like it

In [8]:
a = Tensor([4])
b = Tensor([6])
data = [[1, 2],[3, 4]]
x_data = Tensor(data)
print(x_data)
print(x_data.numpy())


<Tensor <LB (2, 2) dtypes.float op:LoadOps.FROMCPU st:ShapeTracker(shape=(2, 2), views=[View((2, 2), (2, 1), 0, None)])> with grad None>
[[1. 2.]
 [3. 4.]]


## initialise with different data types (int64, float 32)

## from Numpy Arrays

In [9]:
np_array = np.array(data)
x_np = Tensor(np_array)
print(x_np)
print(x_np.numpy())

<Tensor <LB (2, 2) dtypes.int64 op:LoadOps.FROMCPU st:ShapeTracker(shape=(2, 2), views=[View((2, 2), (2, 1), 0, None)])> with grad None>
[[1 2]
 [3 4]]


### interesting. above is type float, here its int64. why?


#### with random or const values

In [10]:

shape = (2,3)
rand_tensor = Tensor.rand(2,3)
print(rand_tensor.shape)

(2, 3)


#### with ones

In [11]:
ones = Tensor.ones(3,4)
ones.numpy()
ones.dtype

dtypes.float

#### with zeros

In [12]:
zero = Tensor.zeros(3,4)
zero.numpy()

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)

#### simple examples of adding tensors in tinygrad

In [13]:
c = Tensor(np.array([1]))
d = np.array([1])
result = a + b
print(result)
print(result.numpy())
print(c)
print(d)

dim2 = Tensor([1,2],[1,5])
print(dim2)

<Tensor <LB (1,) dtypes.float op:BinaryOps.ADD st:ShapeTracker(shape=(1,), views=[View((1,), (0,), 0, None)])> with grad None>
[10.]
<Tensor <LB (1,) dtypes.int64 op:LoadOps.FROMCPU st:ShapeTracker(shape=(1,), views=[View((1,), (0,), 0, None)])> with grad None>
[1]
<Tensor <LB (2,) dtypes.float op:LoadOps.FROMCPU st:ShapeTracker(shape=(2,), views=[View((2,), (1,), 0, None)])> with grad None>


### Attributes of a Tensor

In [14]:

tensor = Tensor.rand(3,4)
print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: (3, 4)
Datatype of tensor: dtypes.float
Device tensor is stored on: CPU


# TODO Write a list of all possible operations on tensors. (link to another page(tensor_operations.py)


In [15]:
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
# why doesnt this work?
# print(f"Last column: {tensor[..., -1]}")
# tensor[:,1] = 0
print(tensor)

First row: <Tensor <LB (4,) dtypes.float op:MovementOps.RESHAPE st:ShapeTracker(shape=(4,), views=[View((4,), (1,), 0, None)])> with grad None>
First column: <Tensor <LB (3,) dtypes.float op:MovementOps.RESHAPE st:ShapeTracker(shape=(3,), views=[View((3,), (4,), 0, None)])> with grad None>
<Tensor <LB (3, 4) dtypes.float op:LoadOps.FROMCPU st:ShapeTracker(shape=(3, 4), views=[View((3, 4), (4, 1), 0, None)])> with grad None>


#### creating an identity matrix.

In [16]:


id1 = Tensor.eye(128)
id1.numpy()

id2 = Tensor.eye(128)
print(id2.numpy())


[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


#### matrix transpose

In [17]:

y1 = Tensor.rand(32,32)
print(y1.numpy())
print(y1.T.numpy())

[[0.7072404  0.13345593 0.44201493 ... 0.04403275 0.4051845  0.00664622]
 [0.05405301 0.6385905  0.77256763 ... 0.5249928  0.85854095 0.9799499 ]
 [0.4368438  0.57177657 0.69131196 ... 0.63610125 0.5391675  0.73815995]
 ...
 [0.52399313 0.4285773  0.9391415  ... 0.775598   0.57152206 0.11852348]
 [0.556052   0.37595594 0.5289173  ... 0.50429004 0.21638668 0.35357308]
 [0.69829196 0.6734528  0.5091572  ... 0.20583594 0.9650903  0.54089785]]
[[0.7072404  0.05405301 0.4368438  ... 0.52399313 0.556052   0.69829196]
 [0.13345593 0.6385905  0.57177657 ... 0.4285773  0.37595594 0.6734528 ]
 [0.44201493 0.77256763 0.69131196 ... 0.9391415  0.5289173  0.5091572 ]
 ...
 [0.04403275 0.5249928  0.63610125 ... 0.775598   0.50429004 0.20583594]
 [0.4051845  0.85854095 0.5391675  ... 0.57152206 0.21638668 0.9650903 ]
 [0.00664622 0.9799499  0.73815995 ... 0.11852348 0.35357308 0.54089785]]


#### matrix multiplication

In [18]:

y2 = Tensor.randn(32,32)
y3 = y1 @ y2
print(y3.numpy())

y4 = y1.matmul(y2)

[[ 4.058259    5.175988    0.8065665  ...  6.979415   -1.1831769
   7.237898  ]
 [ 1.4868002   1.4073349  -0.54212856 ... 10.402195   -1.286941
   9.096824  ]
 [ 0.83593655  4.8065042   1.982448   ...  6.9105268   0.6498976
   3.9251173 ]
 ...
 [-0.9089762  -1.122855    0.2515844  ...  7.3582087  -4.806018
   9.6960745 ]
 [ 3.1613386  -0.42692447 -0.36419648 ...  6.6036935  -3.876374
   9.557668  ]
 [ 1.8641697   4.7868958  -2.0954003  ...  7.826905   -1.8653092
   8.44657   ]]


#### can you do an item()?

#### shape and ndim of tensors. remember, tensors are just np arrays

In [19]:

TENSOR = Tensor([[[1,3,4],
                  [12,2,3],
                  [23,2,3]]])
print(TENSOR.numpy())
TENSOR.numpy().ndim
TENSOR.numpy().shape

[[[ 1.  3.  4.]
  [12.  2.  3.]
  [23.  2.  3.]]]


(1, 3, 3)

#### why does this use full stops instead of commas?

In [41]:

one_to_ten = Tensor.arange(start=0, stop=10, step=1)
print(Tensor.arange(start=0,stop=10,step=0.5).numpy())
print(one_to_ten.numpy().tolist())


[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]
[0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0]


#### create tensor with zeros with same shape as another tensor

In [21]:
print(Tensor.zeros_like(tensor=one_to_ten))

<Tensor <LB (10,) dtypes.float op:LoadOps.CONTIGUOUS st:ShapeTracker(shape=(10,), views=[View((10,), (1,), 0, None)])> with grad None>


#### Tensor datatypes
 Tinygrad does not support changing dtype. it is inferred. You must use numpy to set dtype


In [22]:


data1 = np.array([[1, 2], [3, 4]], dtype='int64')
data2 = np.array([[1, 2], [3, 4]], dtype='int32')
data3 = np.array([[1, 2], [3, 4]], dtype='float32')
Tensor(data1)


<Tensor <LB (2, 2) dtypes.int64 op:LoadOps.FROMCPU st:ShapeTracker(shape=(2, 2), views=[View((2, 2), (2, 1), 0, None)])> with grad None>

Keep in mind that the operations in tinygrad are designed for floating-point data, 
and using integer values might lead to unexpected behavior or errors. 
It is generally recommended to use the default dtype (float32) when working with tinygrad.

In [23]:
data4 = np.array([[1, 2], [3, 4]])
# tensor2 = Tensor(data4, dtype=None, device="cpu", requires_grad=False)
tensor3 = Tensor(data4, dtype=None, device=None, requires_grad=False)
tensor4 = Tensor(data4, dtype=None, requires_grad=False)

you can use cuda (etc. planned) backends. not sure how to do that. sticking to CPU for now

get info about tensor


In [24]:
print(tensor3.dtype)
print(tensor3.shape)
print(tensor3.device)
print(tensor4.device)

dtypes.int64
(2, 2)
None
CPU


Operators Accelerator has to implemet

- UnaryOps(Enum): NOOP = auto(); EXP = auto(); LOG = auto(); CAST = auto() # noqa: E702
-  BinaryOps(Enum): ADD = auto(); SUB = auto(); MUL = auto(); DIV = auto(); POW = auto(); CMPEQ = auto(); MAX = auto() # noqa: E702
-  ReduceOps(Enum): SUM = auto(); MAX = auto() # noqa: E702
-  FusedOps(Enum): MULACC = auto() # noqa: E702
-  LoadOps(Enum): FROMCPU = auto(); CONTIGUOUS = auto(); TOCPU = auto(); CUSTOM = auto() # noqa: E702


Tensor operations
- Addition
- Sub 
- Element wise multiplication
- Division
- Matrix multiplication



In [25]:
AdditionTensor = Tensor([1,2,3])
print(AdditionTensor.numpy())
#AdditionTensor2 = Tensor([1,2,3])
AdditionTensor += 100
print(AdditionTensor.numpy())

[1. 2. 3.]
[101. 102. 103.]


##### can multiply by scalar

In [26]:

MultiplyTensor = AdditionTensor
print(MultiplyTensor.numpy())
print((MultiplyTensor * 10).numpy())
print((MultiplyTensor.mul(10)).numpy())

[101. 102. 103.]
[1010. 1020. 1030.]
[1010. 1020. 1030.]


In [27]:
SubtractionTensor = AdditionTensor
print(SubtractionTensor.numpy())
# print((SubtractionTensor - 10).numpy())
SubtractionTensor -= 10
print(SubtractionTensor.numpy())

[101. 102. 103.]
[91. 92. 93.]


##### element wise mult

In [28]:


elemTensor1 = Tensor([1,2,3])
elemTensor2 = Tensor([1,2,3])
print((elemTensor1 * elemTensor2).numpy())
print((elemTensor1.mul(elemTensor2)).numpy())

[1. 4. 9.]
[1. 4. 9.]


##### matrix dot product

In [29]:

randomTensor = Tensor.randn(3,5)
print((randomTensor @ randomTensor.T).numpy())
print((randomTensor.matmul(randomTensor.T)).numpy())


# print((elemTensor1 @ elemTensor1.T).numpy())

[[ 3.0346458  4.8258753 -2.7468014]
 [ 4.8258753 15.220107  -6.004783 ]
 [-2.7468014 -6.004783   4.051841 ]]
[[ 3.0346458  4.8258753 -2.7468014]
 [ 4.8258753 15.220107  -6.004783 ]
 [-2.7468014 -6.004783   4.051841 ]]


Finding Min, Max, Mean, sum (tensor aggregation)

In [30]:
e = Tensor([1,2,3,4])
print(e.max().numpy())
print(e.min().numpy())
print(e.mean().numpy())

[4.]
[1.]
[2.5]


In [31]:
arange = np.arange(start=1, stop= 10, step =0.5)
print(arange)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


#### Reshaping, squeezing and unsqueezing
Reshape - change shape of matrix
Unsqueeze - 


##### Reshape

In [32]:
f = Tensor.arange(start=1,stop=11,step=0.5)
print(f.numpy())

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5]


In [33]:
f_reshaped1 = f.reshape(4,5)
print(f_reshaped1.numpy())

[[ 1.   1.5  2.   2.5  3. ]
 [ 3.5  4.   4.5  5.   5.5]
 [ 6.   6.5  7.   7.5  8. ]
 [ 8.5  9.   9.5 10.  10.5]]


##### Unsqueeze

In [34]:
print(f.numpy().shape)
f_unsqueezed = f.unsqueeze(1)
f.unsqueeze(0).numpy().shape

(20,)


(1, 20)

##### permute
change order of dimensions
e.g. make 20x1 matrix 1x20

In [35]:
print(f_unsqueezed.numpy())
print(f_unsqueezed.permute(1,0).shape)
f_unsqueezed.shape
print(f_unsqueezed.permute(1,0).numpy())


[[ 1. ]
 [ 1.5]
 [ 2. ]
 [ 2.5]
 [ 3. ]
 [ 3.5]
 [ 4. ]
 [ 4.5]
 [ 5. ]
 [ 5.5]
 [ 6. ]
 [ 6.5]
 [ 7. ]
 [ 7.5]
 [ 8. ]
 [ 8.5]
 [ 9. ]
 [ 9.5]
 [10. ]
 [10.5]]
(1, 20)
[[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
   8.   8.5  9.   9.5 10.  10.5]]


##### for e.g. with image recognition AI
we have image 224*224 pixels * 3 colour channels


In [36]:
image = Tensor.rand(224,224,3)
print(image.shape)

# permute to make colour channels first

image_permuted = image.permute(2,0,1)
print(image_permuted.shape)

(224, 224, 3)
(3, 224, 224)


##### Indexing


In [37]:
print(image[0,0,0].numpy())

[0.05330229]


# Random Seed


In [38]:
h = Tensor.randn(28,28)
i = Tensor.randn(28,28)



In [39]:
Tensor.manual_seed(42)
j = Tensor.randn(28,28)